### ISSUE TITLE
Implement channel join/part function

### ISSUE THREAD

**Issue by simnalamburt** [openirc/openirc#12]
Implement multiple channel speaking features

### TODOs

- [x] At first, we fix the channel that can be talked to exist only #a, #b, #c
- [x] Next, implement channel creation, channel joining, channel leaving function
- [x] Force channel names to start with `#`
- [ ] Error when trying to enter a channel that already exists
- [ ] Handle the "server buffer" specially

Note: `typing` must be separate for each channel. The contents of the #a channel disappear when you change to the #b channel, and when you return to the #b channel from the #b channel, the previous contents must be displayed again.

https://github.com/openirc/openirc/blob/master/client/src/app.elm#L26

--------

I would start by fixing the model part code...

```elm
type alias Model =
  {
    logs : List Line,
    nick : String,
    typing : String
  }
```

like this:

```elm
type alias Channel =
  {
    logs : List Line,
    typing : String
  }

type alias Model =
  {
    nick : String,
    channels : List Channel
  }
```

CC @heejongahn

**Comment by heejongahn** [comment]
Basic channel concept is implemented (see #16)

If our first goal is to resemble IRCCloud, I can think of something like this:

- Server/Channel information is shown at the sidebar (scrollable)
- Each server has a list of joined channel below itself.
- Also, each server has a text input which can be used to (join/create) new channel.
- Each list item (that is, an item representing a channel) has channel name and small `x` button to close the channel.

So the sidebar would seem like:

|**Server A**|
|---|
|Channel 1 [x]|
|Channel 2 [x]|
|Channel 3 [x]|
|___________ (to join/create channel)|

I think we can ignore server for now and assume that there's only one server available. Does this sound ok?

**Comment by simnalamburt** [comment]
Good. #16 has been merged.
