### ISSUE TITLE
'elm-webpack-loader' does not emit compiler warning

### ISSUE THREAD

**Issue by simnalamburt** [openirc/openirc#30]
For now, we have to run commands like below to check compiler warning

```bash
# In '/client' directory...
touch src/* && elm-make src/App.elm --warn && rm index.html
```

- [`elm-webpack-loader`]
- [`node-elm-compiler`]

Those packages are somewhat outdated. We have to fork both project to let [`elm-webpack-loader`] emit compiler warning.

### Roadmap
- [x] Fork both project into `@openirc` namespace.
  1. http://blog.npmjs.org/post/116936804365/solving-npms-hard-problem-naming-packages
  2. https://docs.npmjs.com/getting-started/scoped-packages
- [x] Let `openirc/openirc` and `openirc/elm-webpack-loader` depend on github repository of `openirc/elm-webpack-loader` and `openirc/node-elm-compiler`, respectively
- [ ] Abandon npm, adopt yarn for both [`elm-webpack-loader`] and [`node-elm-compiler`]. (It means, drop support for node 0.12. node 0.12 will be out of support in few weeks.)
- [ ] Update both project to use Elm 0.18
- [ ] Fix unit test and CI. [`.travis.yml`](https://github.com/rtfeldman/node-elm-compiler/blob/master/.travis.yml) of [`node-elm-compiler`] is unnecessarily complicated
  - 지금 [`node-elm-compiler`] 보면 elm을 깔아야 테스트가 실행되게 해놔서 테스트도 불편하고, 여러 버전의 elm에 대고 동시에 테스트하는것도 곤란한 상태인데, 그렇게 할 필요 없다. 그냥 npm으로 elm을 로컬에 설치하게 하면 된다. 이때 시스템에 설치된 elm과 npm으로 설치한 elm이 섞이지 않도록 주의할것.
- [ ] Do any other required housekeeping
- [ ] Make a new API for [`node-elm-compiler`] to handle compiler warning
- [ ] Add unit tests for `--warn` option
- [ ] Make a pull request to the both project. But hopefully I want one of me and @heejongahn to be a collaborator of those projects.
- [ ] Make `--warn` options to be true as a default in [`elm-webpack-loader`]

[`elm-webpack-loader`]: https://github.com/rtfeldman/elm-webpack-loader
[`node-elm-compiler`]: https://github.com/rtfeldman/node-elm-compiler

**Comment by simnalamburt** [comment]
Related conversation

```IRC
<~지현> 희종: Busy?
<희종> 좀 이따 나가긴 할건데
<희종> 어차피 나가서 까페갈 것
<희종> 와이
<~지현> Shall we fork node-elm-compiler ?
<희종> 오호...
<~지현> https://github.com/rtfeldman/node-elm-compiler
<희종> 왜?
<~지현> 워닝을
<~지현> 출력 안해줘
<~지현> 웹팩한테
<~지현> elm-make한테 '--warn' arg를 준 뒤, stderr에 뭔가 출력되면 그걸 워닝이라고 인식하고
<~지현> 웹팩이 주는 emitWarning() 함수를 호출시켜주면 되는데
<~지현> 그걸 안함
<희종> 그렇군
<희종> 그걸 얘가 하는건가
<~지현> ㅇㅇ
<~지현> PR날리기 귀찮
<희종> 그 말만 들어서는 별로 안 어렵게 느껴지는데
<희종> 내가 해볼까
<~지현> 저 패키지가 좀 outdated 되어있음
<희종> 나는 워닝을 썰테니 넌 mqtt를 쓰거라(?)
<~지현> 그래서 할꺼면
<~지현> elm-webpack-loader랑 node-elm-compiler를 둘다
<~지현> openirc 밑으로 포크한다음에
<~지현> 당분간은 package.json에
<~지현> @openirc/elm-webpack-loader
<~지현> 이런식으로 살고
<~지현> 다 머지되면
<~지현> elm-webpack-loader 로 돌아가면 될듯
<~지현> 저거 자잘하게 고칠게 많음
<~지현> 유닛테스트도 망가져있고
<~지현> npm도 yarn으로 바꾸고
<~지현> 등등
<~지현> mqtt랑 독립적으로 할 수 있는 작업이긴 한데
<~지현> 워닝 안뜨는게 성가심
<~지현> 일단 이슈에 넣어놓자
<~지현> 하면 좋을듯
<~지현> 한번 봐보셈
<희종> ㅇㅇ
<희종> 나 이따 까페가서
<희종> 뷸세
<희종> 볼게
```

**Comment by heejongahn** [comment]
We decided to rely on github repository url as a dependency source, instead of npm scoped package.

```
12:44:34       희종 | 궁금한게 몇 개 있는데
12:44:43       희종 | 일단 yarn에서 error An unexpected error occurred: "https://registry.yarnpkg.com/@openirc%2fnode-elm-compiler: You must
                    | be logged in to publish packages". 이거
12:44:46       희종 | https://github.com/yarnpkg/yarn/issues/521 이거랑 관련된거임?
12:45:11       희종 | yarn publish --access=public 했을 때 뜨는건데
12:45:25      i지현 | yarn publish 문제있음
12:45:33      i지현 | 저거 고쳐지기 전까지만
12:45:33       희종 | 로그인 그냥 openirc / 이메일 없이 했는데, 그 전에 별도의 절차같은게 필요한가
12:45:40      i지현 | 퍼블리시할때만 npm쓰셈
12:45:45      i지현 | 아니 절차 필요없음
12:45:53       희종 | 그럼 그건 됐고
12:46:11       희종 | 포크 뜬 패키지에 author, license 수정해야되는건 필수사항인가
12:46:22      i지현 | 아니
12:46:39       희종 | 그럼 그건 일단 냅두고 개발부터 해야겠군
12:46:43      i지현 | 아니면
12:46:44      i지현 | 귀찮으면
12:46:48      i지현 | npm에 안올리고
12:46:54      i지현 | package.json에
12:46:58      i지현 | git 경로 써도 됨
12:47:02      i지현 | 차라리 그게낫겠다
12:47:04      i지현 | 그렇게하자
12:47:04       희종 | ㅇㅇ
12:47:05       희종 | 그렇게하자
12:47:07       희종 | 그게 나을듯
```

**Comment by simnalamburt** [comment]
@heejongahn Let's abandon or postpone this issue. I found that `elm-make`'s compiler warning message is not that much useful. It does not worth the effort.
