### ISSUE TITLE
Implement round-trip recognition

### ISSUE THREAD

**Issue by simnalamburt** [openirc/openirc#39]
Indicate that the transfer is completed when the message finishes the round-trip.

![](http://www.zerodollartips.com/wp-content/uploads/2016/06/delivered-imessage.jpg)

### TODOs
- [x] ~~lines: List Line  ->  lines: Array Line~~ &rarr; Not going to do it
- [x] ~~Remove `LineStatus` type from `Line`~~ &rarr; Not going to do it
- [ ] 지금 새 메세지 들어올떄마다 `list ++ [ new ]` 이렇게 하고있는데 이거 `new::list` 로 고치기
- [ ] TransmissionStatus: Dict Int LineStatus 타입 생성
- [ ] Rename: ReceiveLine -> ReceivePayload
- [ ] ReceivePayload 에서 Session으로 비교하여 TransmissionStatus 업데이트하는 코드 넣기

**Comment by simnalamburt** [comment]
I'm working on it at [`mqtt`](https://github.com/openirc/openirc/tree/mqtt) branch.

**Comment by simnalamburt** [comment]
We're going to use [blacktaxi/elm-random-secure](https://github.com/blacktaxi/elm-random-secure) to as a CSPRNG

**Comment by simnalamburt** [comment]
We just forked [blacktaxi/elm-random-secure](https://github.com/blacktaxi/elm-random-secure) into [openirc/elm-random-secure](https://github.com/openirc/elm-random-secure).

#### TODO
- [ ] Make it work in Elm 0.18
- [ ] Publish it as a native module. 
- [ ] Embed it in openirc project

###### References
- https://github.com/elm-lang/package.elm-lang.org/issues
- http://reversemicrowave.me/blog/2016/03/04/elm-secure-random/
