### ISSUE TITLE
Initialize session's numeric id randomly

### ISSUE THREAD

**Issue by simnalamburt** [openirc/openirc#40]
We just forked [blacktaxi/elm-random-secure](https://github.com/blacktaxi/elm-random-secure) into [openirc/elm-random-secure]. We're going to use it as a CSPRNG.

#### TODO
- [x] ~~Make [openirc/elm-console] work with Elm 0.17~~ &rarr; Won't do this
- [x] ~~Make [openirc/elm-console] work with Elm 0.18~~ &rarr; Won't do this
- [x] ~~Make [openirc/elm-crypto] properly tested with Elm 0.17~~ &rarr; Won't do this
- [x] Introduce basic CI to the [openirc/elm-crypto]
- [ ] Make [openirc/elm-crypto] work with Elm 0.18
- [x] ~~Make [openirc/elm-crypto] properly tested~~ &rarr; https://github.com/openirc/elm-crypto/issues/2
- [x] ~~Resolve all TODOs of [openirc/elm-crypto]~~ &rarr; [elm-crypto issue tracker](https://github.com/openirc/elm-crypto/issues)
- [ ] Publish it as a native module. 
- [ ] Embed it in openirc project

###### References
- https://github.com/elm-lang/package.elm-lang.org/issues
- http://reversemicrowave.me/blog/2016/03/04/elm-secure-random/

[openirc/elm-crypto]: https://github.com/openirc/elm-crypto
[openirc/elm-console]: https://github.com/openirc/elm-console

**Comment by simnalamburt** [comment]
나중에는 고유식별자 발급/환수하는 서버를 만드는것이 낫겠다. 그 서버에서 확실하게 겹치지 않는것이 보장되는 ID를 주면 그걸 쓰자.

**Comment by xtendo-org** [comment]
Later, @simnalamburt suggested this idea: The clients will first have to authenticate (log in) anyway, and during that process the server would be able to issue a unique ID, which solves the "how to identify multiple clients of a same user" problem altogether.
