### ISSUE TITLE
Resolve false positive from Travis CI

### ISSUE THREAD

**Issue by simnalamburt** [openirc/openirc#41]
From https://travis-ci.org/openirc/openirc/builds/190217678 ...

![2017-01-09 9 11 41](https://cloud.githubusercontent.com/assets/4435445/21766182/4359f5d0-d6b0-11e6-9c74-de3c9ec0991d.png)

This is wrong.

### TODOs
- [x] Check if `$?` is nonzero value when there're compile errors.
- [x] Check if `$?` is nonzero value when there're plugin errors.
- [x] Check if exit status is properly preserved even if it is executed under [`sysconfcpus`](https://github.com/obmarg/libsysconfcpus).

###### References
- https://github.com/webpack/webpack/issues/708
- https://github.com/TiddoLangerak/webpack-fail-plugin
