### ISSUE TITLE
Separate debug/production mode

### ISSUE THREAD

**Issue by simnalamburt** [openirc/openirc#8]
#### TODOs
- [ ] Turn off the server's own static file serving
- [ ] Turn off server debug messages
- [x] Make the client-side codes as small as possible
- [ ] What else?
